### PR TITLE
Fix build with GCC 14.1

### LINKED ISSUE #509: Fails to build with GCC 14.1.1 with `error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]`
With GCC 14.1.1, build fails:

```
[...]
ctl-cli.c: In function ‘cli_printf_time_prefix’:
ctl-cli.c:104:17: error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  104 |                 gettimeofday(&tv, NULL);
      |                 ^~~~~~~~~~~~
ctl-cli.c: In function ‘cli_printf_time_prefix’:
ctl-cli.c:104:17: error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  104 |                 gettimeofday(&tv, NULL);
      |                 ^~~~~~~~~~~~
make[3]: *** [Makefile:592: miracle_wifictl-ctl-cli.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:522: miracle_sinkctl-ctl-cli.o] Error 1
make[3]: Leaving directory '/var/cache/makepkg/build/miraclecast-nosystemd-git/src/miraclecast/src/ctl'
make[2]: *** [Makefile:539: all-recursive] Error 1
make[2]: Leaving directory '/var/cache/makepkg/build/miraclecast-nosystemd-git/src/miraclecast/src'
make[1]: *** [Makefile:423: all-recursive] Error 1
make[1]: Leaving directory '/var/cache/makepkg/build/miraclecast-nosystemd-git/src/miraclecast'
make: *** [Makefile:355: all] Error 2
```

Regards!

(Adding `-Wno-error=implicit-function-declaration` to `CFLAGS` / `CXXFLAGS` does work around the issue, but the code should be fixed.)

### PR DESCRIPTION
**Pull request by MarkMuth**
Compiling with `gcc (GCC) 14.1.1 20240507` raised the following warning:

`error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]`

Adding `#include <sys/time.h>` according to `man gettimeofday` fixes #509.

### CODE REVIEW

**Comment by albfan** [comment]
Thanks, I credit you on c83802f as unneeded time include needs to be removed too
