### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by pulkin** [albfan/miraclecast#458]
My build on RPI 3 v1.2 latest raspbian was failing with this:
```
cd /home/pulkin/miraclecast/build/src/dhcp && /usr/bin/cmake -E cmake_link_script CMakeFiles/miracle-dhcp.dir/link.txt --verbose=1
/usr/bin/cc -std=gnu11 -std=gnu11  -rdynamic CMakeFiles/miracle-dhcp.dir/dhcp.c.o CMakeFiles/miracle-dhcp.dir/common.c.o CMakeFiles/miracle-dhcp.dir/ipv4ll.c.o CMakeFiles/miracle-dhcp.dir/client.c.o CMakeFiles/miracle-dhcp.dir/server.c.o -o miracle-dhcp  -ludev -lm -lglib-2.0 ../shared/libmiracle-shared.a -lsystemd 
/usr/bin/ld: ../shared/libmiracle-shared.a(shl_log.c.o): in function `log__submit':
shl_log.c:(.text+0x274): undefined reference to `lrint'
collect2: error: ld returned 1 exit status
```
I had to add `target_link_libraries(miracle-shared m)` to `src/shared/CMakeLists.txt` presumably because of
```bash
$ grep lrint *
shl_log.c:		millisec = lrint(tv.tv_usec/1000.0);
```

**Comment by albfan** [comment]
yes, I think that is usually glibc devel package

**Comment by albfan** [comment]
closing as find dependencies is outside of scope.

I accept any patches relates with buildsystem checks for dependencies

**Comment by smilesun** [comment]
why not make a pull request for this or each user should do this again?

**Comment by albfan** [comment]
Have a dependency is not something a code repository can control.
